-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

 NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = 0
 NDefines.NGovernment.GOVERNMENT_REFORM_CHANGE_PROGRESS_COST = 25.0
 NDefines.NGovernment.GOVERNMENT_REFORM_COST_CENTRALIZE_STATE = 50.0
 NDefines.NGovernment.CENTRALIZE_STATE_REDUCTION = 33
 NDefines.NGovernment.CENTRALIZE_STATE_YEARS = 3
 NDefines.NGovernment.CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0
 NDefines.NGovernment.CONCENTRATE_DEVELOPMENT_OTHER_STATE_PROVINCES_PROPORTION = 0
 NDefines.NGovernment.FREE_CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0
 NDefines.NGovernment.FREE_CONCENTRATE_DEVELOPMENT_OTHER_STATE_PROVINCES_PROPORTION = 0
 NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 0.64
 NDefines.NMilitary.DEFAULT_WARGOAL_WARSCORE_BONUS = 8
 NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
 NDefines.NMilitary.PARTICIPATION_SCORE_BLOCKADE = 0.003
 NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 1.5
 NDefines.NMilitary.SLACKEN_AP_DROP = 0.1
 NDefines.NMilitary.MARINE_SHOCK_DAMAGE_TAKEN = 0.05
 NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -150
 NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
 NDefines.NDiplomacy.STABHIT_FOR_BREAKING_ALLIANCE_IN_WAR = 0
 NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 15
 NDefines.NCountry.MONTHS_FOR_MAX_MP_ALERT = 5
 NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -30
 NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 0.5
 NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
 NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 120
 NDefines.NCountry.ABANDON_IDEAGROUP_REFUND = 0.20
 NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.05
 NDefines.NMilitary.MERCENARY_MAX_REGIMENTS = 40
 NDefines.NEconomy.CONVERSION_ZEAL_DURATION = 5475