-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

 NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = 0
 NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 0.64
 NDefines.NMilitary.DEFAULT_WARGOAL_WARSCORE_BONUS = 8
 NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
 NDefines.NMilitary.PARTICIPATION_SCORE_BLOCKADE = 0.003
 NDefines.NMilitary.BACK_LINE_MORALE_DAMAGE_TAKEN_MODIFIER = 0.1
 NDefines.NMilitary.BACK_LINE_REINFORCE_SPEED = 6
 NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 4 --twice as high
 -- NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 1.5 RIP in 1.35
 NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
 NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
 NDefines.NDiplomacy.STABHIT_FOR_BREAKING_ALLIANCE_IN_WAR = 0
 NDefines.NDiplomacy.HRE_FOREIGN_CONTROL_PENALTY = -0.01
 NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 15
 NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 1
 NDefines.NCountry.MONTHS_FOR_MAX_MP_ALERT = 6
 NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -30
 NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 0.5
 NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
 NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 120
 NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.05
 -- NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 40
 NDefines.NEconomy.CONVERSION_ZEAL_DURATION = 5475
 NDefines.NEconomy.CARAVAN_POWER_MAX = 25
 NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.03 --50% more than previous cost per tech